name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-iamge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: Make venv
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      
      - name: Build & Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/msa-recommend:24.07.04 .
          docker push ${{ secrets.DOCKER_USERNAME }}/msa-recommend:24.07.04
